2024-12-29 04:17:28.130  3801-3838  GoogleApiManager        com.devlopershankar.onefixedjob      E  Failed to get service from broker. 
                                                                                                    java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3242)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3226)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3209)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3151)
                                                                                                    	at anfm.a(:com.google.android.gms@244534038@24.45.34 (260800-699214190):36)
                                                                                                    	at andt.z(:com.google.android.gms@244534038@24.45.34 (260800-699214190):143)
                                                                                                    	at amlc.run(:com.google.android.gms@244534038@24.45.34 (260800-699214190):54)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at btaq.mI(:com.google.android.gms@244534038@24.45.34 (260800-699214190):1)
                                                                                                    	at btaq.dispatchMessage(:com.google.android.gms@244534038@24.45.34 (260800-699214190):5)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:85)
